export default {
  "View Channel": "ViewChannel",
  "Manage Channel": "ManageChannels",
  "Manage Permissions": "ManageRoles",
  "Manage Webhooks": "ManageWebhooks",
  "Create Invite": "CreateInstantInvite",
  "Send Messages": "SendMessages",
  "Send Messages in Threads": "SendMessagesInThreads",
  "Create Public Threads": "CreatePublicThreads",
  "Create Private Threads": "CreatePrivateThreads",
  "Embed Links": "EmbedLinks",
  "Attach Files": "AttachFiles",
  "Add Reactions": "AddReactions",
  "Use External Emoji": "UseExternalEmojis",
  "Use External Stickers": "UseExternalStickers",
  "Mention @everyone, @here, and All Roles": "MentionEveryone",
  "Manage Messages": "ManageMessages",
  "Manage Threads": "ManageThreads",
  "Read Message History": "ReadMessageHistory",
  "Send Text-to-Speech Messages": "SendTtsMessages",
  "Use Application Commands": "UseApplicationCommands",
}